# Generated by Django 4.1.3 on 2023-03-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_images', models.ImageField(upload_to='admin_banners/')),
            ],
        ),
    ]
